# Generated by Django 5.0.14 on 2026-06-25 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("graph", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="graphedge",
            name="weight",
            field=models.FloatField(default=1.0),
        ),
    ]
