# Generated by Django 5.0.14 on 2026-06-18 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("alerts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="alert",
            name="vendor",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
