# Generated by Django 5.0.14 on 2026-06-17 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="APIAsset",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("endpoint", models.CharField(max_length=255)),
                ("auth", models.BooleanField(default=True)),
                ("tls", models.BooleanField(default=True)),
                ("owner", models.CharField(max_length=100)),
                ("status", models.CharField(max_length=50)),
                ("last_used", models.DateField()),
                ("risk_score", models.FloatField(default=0)),
            ],
        ),
    ]
