# Generated by Django 5.0.14 on 2026-06-19 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api_security", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="EnterpriseAPI",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("endpoint", models.CharField(max_length=500)),
                ("auth", models.BooleanField(default=False)),
                ("tls", models.BooleanField(default=False)),
                ("rate_limit", models.BooleanField(default=False)),
                ("status", models.CharField(max_length=50)),
                ("owner", models.CharField(max_length=255)),
                ("last_used", models.DateField()),
                ("risk_score", models.FloatField(default=0)),
            ],
        ),
        migrations.DeleteModel(
            name="APIAsset",
        ),
    ]
