# Generated by Django 5.0.14 on 2026-06-20 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api_security", "0002_enterpriseapi_delete_apiasset"),
    ]

    operations = [
        migrations.AddField(
            model_name="enterpriseapi",
            name="vendor",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
