# Generated by Django 5.0.14 on 2026-06-17 09:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Vendor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("country", models.CharField(max_length=100)),
                ("industry", models.CharField(max_length=100)),
                ("financial_score", models.FloatField(default=0)),
                ("cyber_score", models.FloatField(default=0)),
                ("regulatory_score", models.FloatField(default=0)),
                ("overall_score", models.FloatField(default=0)),
                ("last_updated", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="VendorNews",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=500)),
                ("content", models.TextField()),
                ("source", models.CharField(max_length=200)),
                ("date", models.DateTimeField()),
                ("url", models.URLField()),
                ("sentiment", models.CharField(max_length=50)),
                ("risk_type", models.CharField(max_length=100)),
                ("severity", models.CharField(max_length=50)),
                (
                    "vendor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="vendors.vendor"
                    ),
                ),
            ],
        ),
    ]
