# Generated by Django 5.0.14 on 2026-06-18 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vendors", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="vendor",
            old_name="cyber_score",
            new_name="compliance",
        ),
        migrations.RenameField(
            model_name="vendor",
            old_name="financial_score",
            new_name="cybersecurity",
        ),
        migrations.RenameField(
            model_name="vendor",
            old_name="overall_score",
            new_name="financial",
        ),
        migrations.RenameField(
            model_name="vendor",
            old_name="regulatory_score",
            new_name="operational",
        ),
        migrations.RemoveField(
            model_name="vendor",
            name="country",
        ),
        migrations.RemoveField(
            model_name="vendor",
            name="industry",
        ),
        migrations.RemoveField(
            model_name="vendornews",
            name="content",
        ),
        migrations.RemoveField(
            model_name="vendornews",
            name="date",
        ),
        migrations.RemoveField(
            model_name="vendornews",
            name="risk_type",
        ),
        migrations.RemoveField(
            model_name="vendornews",
            name="sentiment",
        ),
        migrations.RemoveField(
            model_name="vendornews",
            name="source",
        ),
        migrations.RemoveField(
            model_name="vendornews",
            name="url",
        ),
        migrations.AddField(
            model_name="vendor",
            name="risk_events_count",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="vendor",
            name="risk_level",
            field=models.CharField(default="Low", max_length=50),
        ),
        migrations.AddField(
            model_name="vendor",
            name="risk_score",
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="vendornews",
            name="category",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="vendornews",
            name="link",
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name="vendornews",
            name="published",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="vendornews",
            name="risk_category",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="vendornews",
            name="text",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="vendornews",
            name="severity",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="vendornews",
            name="title",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="vendornews",
            name="vendor",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
