# Generated by Django 5.0.14 on 2026-06-19 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vendors", "0002_rename_cyber_score_vendor_compliance_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="CyberNews",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("vendor", models.CharField(max_length=255)),
                ("title", models.TextField()),
                ("published", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "risk_category",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("cyber_hits", models.IntegerField(default=0)),
                ("financial_hits", models.IntegerField(default=0)),
                ("compliance_hits", models.IntegerField(default=0)),
                ("operational_hits", models.IntegerField(default=0)),
            ],
        ),
    ]
